'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Concepto
    Public Property id_concepto As Integer
    Public Property descripcion As String
    Public Property tipoconcepto As Nullable(Of Integer)
    Public Property valor As Nullable(Of Decimal)
    Public Property estado As String
    Public Property codigo As Nullable(Of Integer)
    Public Property estadobaja As Nullable(Of Boolean)

    Public Overridable Property Tipo_Concepto As Tipo_Concepto
    Public Overridable Property Sueldo_Det As ICollection(Of Sueldo_Det) = New HashSet(Of Sueldo_Det)

End Class
