'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contrato
    Public Property id_contrato As Integer
    Public Property fechac As Date
    Public Property descripcion As String
    Public Property periodo As Nullable(Of Integer)
    Public Property fecha_emision As Nullable(Of Date)
    Public Property fecha_vencimiento As Nullable(Of Date)
    Public Property tipo As Nullable(Of Integer)
    Public Property estadobaja As Nullable(Of Boolean)
    Public Property idempleado As Nullable(Of Integer)

    Public Overridable Property Empleado As Empleado
    Public Overridable Property Tipo_Contrato As Tipo_Contrato

End Class
