'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Convenio
    Public Property id_convenio As Integer
    Public Property descripcion As String
    Public Property estadobaja As Nullable(Of Boolean)

    Public Overridable Property Actividad As ICollection(Of Actividad) = New HashSet(Of Actividad)
    Public Overridable Property CategoriaC As ICollection(Of CategoriaC) = New HashSet(Of CategoriaC)

End Class
