'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property id_empleado As Integer
    Public Property cuil As String
    Public Property nombre As String
    Public Property apellido As String
    Public Property dni As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property fecha_ing As Nullable(Of Date)
    Public Property fecha_egres As Nullable(Of Date)
    Public Property fecha_nac As Nullable(Of Date)
    Public Property estado_civil As Nullable(Of Integer)
    Public Property hijos As Nullable(Of Integer)
    Public Property empresa As Nullable(Of Integer)
    Public Property antiguedad As Nullable(Of Integer)
    Public Property estadobaja As Nullable(Of Boolean)
    Public Property id_categoria As Nullable(Of Integer)
    Public Property id_actividad As Nullable(Of Integer)
    Public Property obras As Nullable(Of Integer)

    Public Overridable Property Actividad As Actividad
    Public Overridable Property Contrato As ICollection(Of Contrato) = New HashSet(Of Contrato)
    Public Overridable Property Empresa1 As Empresa
    Public Overridable Property Estado_Civil1 As Estado_Civil
    Public Overridable Property Obra_Social As Obra_Social
    Public Overridable Property Sueldo_Cab As ICollection(Of Sueldo_Cab) = New HashSet(Of Sueldo_Cab)

End Class
