'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class KoutSueldosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=KoutSueldosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Actividad() As DbSet(Of Actividad)
    Public Overridable Property Banco() As DbSet(Of Banco)
    Public Overridable Property CategoriaC() As DbSet(Of CategoriaC)
    Public Overridable Property Concepto() As DbSet(Of Concepto)
    Public Overridable Property Contrato() As DbSet(Of Contrato)
    Public Overridable Property Convenio() As DbSet(Of Convenio)
    Public Overridable Property Empleado() As DbSet(Of Empleado)
    Public Overridable Property Empresa() As DbSet(Of Empresa)
    Public Overridable Property Empresa_Sucursal() As DbSet(Of Empresa_Sucursal)
    Public Overridable Property Estado_Civil() As DbSet(Of Estado_Civil)
    Public Overridable Property Localidad() As DbSet(Of Localidad)
    Public Overridable Property Obra_Social() As DbSet(Of Obra_Social)
    Public Overridable Property Periodo() As DbSet(Of Periodo)
    Public Overridable Property Provincia() As DbSet(Of Provincia)
    Public Overridable Property Razon_Social() As DbSet(Of Razon_Social)
    Public Overridable Property Remuneraciones() As DbSet(Of Remuneraciones)
    Public Overridable Property Sueldo_Cab() As DbSet(Of Sueldo_Cab)
    Public Overridable Property Sueldo_Det() As DbSet(Of Sueldo_Det)
    Public Overridable Property Tipo_Concepto() As DbSet(Of Tipo_Concepto)
    Public Overridable Property Tipo_Contrato() As DbSet(Of Tipo_Contrato)
    Public Overridable Property Unidad() As DbSet(Of Unidad)

End Class
