'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Remuneraciones
    Public Property id_remuneraciones As Integer
    Public Property valor As Nullable(Of Decimal)
    Public Property fecha As Nullable(Of Date)
    Public Property actividad As Nullable(Of Integer)
    Public Property unidad As Nullable(Of Integer)
    Public Property estadobaja As Nullable(Of Boolean)

    Public Overridable Property Actividad1 As Actividad

End Class
