'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sueldo_Cab
    Public Property id_reciboC As Integer
    Public Property fecha As Date
    Public Property id_empresa As Nullable(Of Integer)
    Public Property periodo As Nullable(Of Integer)
    Public Property periodoLiq As Nullable(Of Date)
    Public Property total As Nullable(Of Decimal)
    Public Property empleado As Nullable(Of Integer)
    Public Property id_banco As Nullable(Of Integer)
    Public Property ciudad As String
    Public Property id_provincia As Nullable(Of Integer)
    Public Property id_localidad As Nullable(Of Integer)
    Public Property sucursalemp As Nullable(Of Integer)
    Public Property total_bruto As Nullable(Of Decimal)
    Public Property total_neto As Nullable(Of Decimal)
    Public Property estadobaja As Nullable(Of Boolean)

    Public Overridable Property Banco As Banco
    Public Overridable Property Empleado1 As Empleado
    Public Overridable Property Empresa_Sucursal As Empresa_Sucursal
    Public Overridable Property Localidad As Localidad
    Public Overridable Property Periodo1 As Periodo
    Public Overridable Property Sueldo_Det As ICollection(Of Sueldo_Det) = New HashSet(Of Sueldo_Det)

End Class
