'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sueldo_Det
    Public Property id_reciboc As Integer
    Public Property fecha As Date
    Public Property id_recibo_det As Integer
    Public Property concepto As Nullable(Of Integer)
    Public Property cantidad As Nullable(Of Integer)
    Public Property unidad As String
    Public Property importe As Nullable(Of Decimal)
    Public Property subtotal As Nullable(Of Decimal)
    Public Property estadobaja As Nullable(Of Boolean)

    Public Overridable Property Concepto1 As Concepto
    Public Overridable Property Sueldo_Cab As Sueldo_Cab

End Class
